### ISSUE TITLE
Bug Report: Rendering Corruption Triggered by Enhanced Quarry

### ISSUE THREAD

**Issue by NZehnder** [PTOM76/EnhancedQuarries#37]
📌 Summary

Using the Enhanced Quarry from Enhanced Quarries v1.5.4 causes surrounding or adjacent chunks to fail rendering after unloading and returning to the area. Blocks remain interactable and mined, but are invisible or "ghosted". The rendering state only recovers after removing the quarry and reloading the chunk.

🧪 Reproduction Steps

1. Place an Enhanced Quarry and power it.
2. Let it run for a few seconds/minutes.
3. Unload the chunk (e.g. teleport far away using /tp or a Waystone).
4. Return to the quarry area.
5. Observe corrupted rendering — invisible terrain or void with entities floating.
6. Break the quarry and reload the chunk (via teleport or log out/in).
7. Rendering restores as expected.

💥 Expected vs Actual Behavior

Expected | Actual
-- | --
Quarry chunks should reload normally. | Terrain is invisible or doesn't render.
Blocks interact and render normally. | Blocks are "there" but invisible.
Breaking quarry shouldn't affect chunks. | Breaking quarry + reload restores rendering.

🔧 Environment

- Minecraft Version: 1.20.1 (Fabric)
- Enhanced Quarries Version: 1.5.4
- Java: Java 17 (PrismLauncher runtime)
- Launcher: PrismLauncher 9.4
- Render Mods: Issue reproduced and reproducible with/without Sodium, REI, or shaders

📷 Visual Evidence

Images show:

Quarry active:
![Image](https://github.com/user-attachments/assets/57ac1afd-d080-4936-82cc-8a3fc49d2d66)

Chunks not rendering:
![Image](https://github.com/user-attachments/assets/91c739ed-3097-45e9-bbbe-2acc0bfe8440)

Quarry in void state:
![Image](https://github.com/user-attachments/assets/47d0df97-f208-4bfe-9302-4be7606056d9)

Visuals returning after removal and reload:
![Image](https://github.com/user-attachments/assets/e7136c38-e584-474d-ba06-c1de2cfd18fc)

📄 Logs

Log excerpt (with -Dfabric.log.level=debug enabled) contains repeated lines like:

```
BlockEntityRenderDispatcher.render() skipped rendering block entity at BlockPos{x=..., y=..., z=...}
``` 

No crash or fatal error, but renderer appears to silently bail on rendering chunks.
Full Log below: 
[latest.log](https://github.com/user-attachments/files/20302418/latest.log)

💾 Additional Info

Let me know if you need a test world or modpack folder. I can reproduce the issue reliably.

**Comment by NZehnder** [comment]
Update after testing version 1.5.6:

    Mod version: Enhanced Quarries 1.5.6

    Library: MCPitanLib 3.2.5

    Minecraft: 1.20.1 (Fabric)

❌ However, the chunk rendering issue still happens exactly as described:

If a quarry is running and the chunk is unloaded and then reloaded (e.g., via teleport or Waystone), that area becomes invisible / unrendered.
Breaking the quarry and reloading the chunk causes it to render normally again.

**Comment by PTOM76** [comment]
I tried this issue and it seems to crash in 1.20.4, so I fixed it, did it get any better?

**Comment by NZehnder** [comment]
Tried in 1.20.4 too there it seems to be fixed, unfortunally i cant update all my mods to 1.20.4 
Still getting: 
```java
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4970$class_4971.method_26204(net.minecraft.class_2680)" because "block" is null
	at net.petercashel.enhancedquarries.block.entity.QuarryBlockEntity.method_16896(QuarryBlockEntity.java:223)
	at net.minecraft.class_1937.method_18471(class_1937.java:648)
	at net.minecraft.class_3218.method_18765(class_3218.java:732)
	...

``` 
Just to clarify — the crash isn’t limited to existing worlds. I can reproduce it in completely new worlds as well, so it doesn't appear to be caused by leftover data or world corruption.

**Comment by PTOM76** [comment]
There seems to be something wrong with that crash report. I couldn't reproduce it, but I fixed it as I thought it might be.
