### ISSUE TITLE
[bug] Normal marker

### ISSUE THREAD

**Issue by Romz24** [PTOM76/EnhancedQuarries#7]
Because of the grass, when we place the marker, it is placed crookedly and weighs in the air. This looks like a bug, and it looks strange.

Video:
https://youtu.be/K2VXv_bTCs8

It would also be nice to turn off collisions for them _(if I'm not mistaken, this is implemented in Buildcraft)_ so that we can safely go through and not run into them while moving.

**Comment by PTOM76** [comment]
Both have been fixed. It will be reflected in the next release.

**Comment by Romz24** [comment]
@PTOM76 
It seems this is still not fully fixed. I am using version 1.2.0-RC2 and the problem remains partially. If you try to put a marker on a sunflower, the problem repeats.

![image](https://user-images.githubusercontent.com/2458113/134825416-f36f8ed5-7b82-4f53-9962-a367405264b2.png)

**Comment by Romz24** [comment]
I also noticed a bug with **Optimum Process Quarry**, it seems the frame is not being built correctly for it. I understand that this is not a stable version yet, but I decided to inform you about it.

![image](https://user-images.githubusercontent.com/2458113/134825504-9f7092c5-5dbe-4647-bad0-c6bdd3f1b1c1.png)

**Comment by PTOM76** [comment]
I don't think there is any problem with sunflowers.
The specifications are the same as for logs.
![スクリーンショット 2021-09-27 072211](https://user-images.githubusercontent.com/58260965/134826106-91cb5a42-047e-4576-88eb-b49fdcaf1af7.png)
I know about Optimum Process Quarry.
It will be fixed in the next release.

**Comment by Romz24** [comment]
How is **Optimum Process Quarry** different from other quarries? I was just trying to test, and I only realized that it ignores the blocks we placed inside the pit.

![image](https://user-images.githubusercontent.com/2458113/134826386-27183c8d-c1f6-4a70-91e5-29d3a0300b83.png)

**Comment by PTOM76** [comment]
Optimum Process Quarry omits some processing to make it lighter.
Normal Quarry detects and processes all blocks within range.
I'm struggling to fix a bug in the Optimum Process Quarry frame.

**Comment by Romz24** [comment]
Why did you decide to create different types of quarries? It would be more convenient to have one type of quarry, and different improvement modules for it (liquid removal / acceleration, etc.). It would also be nice to have a GUI interface for the quarry to install those modules there.

**Comment by PTOM76** [comment]
This is because I reproduce a mod called Compact Engine.
I'll think about the GUI interface.

**Comment by PTOM76** [comment]
Fixed a bug where the frame was not placed.
